### ISSUE TITLE
Suggestion: rename "delete()" to "remove()" and switch to plain functions

### ISSUE THREAD

**Issue by emilis** [WebOrigami/origami#2]
https://github.com/GraphOrigami/origami/blob/5df76cfccb19ff244883ff42fa9f4be9c0617c0d/packages/core/src/DictionaryHelpers.js#L10-L13

Using static methods instead of plain functions in the language that brought first-class functions to the mainstream and has problematic OOP looks weird.

Also this would prevent tree-shaking?

The reason is understandable, but have you considered renaming `delete()` to `remove()`?

**Comment by JanMiksovsky** [comment]
You're right. I'd really wanted to use `delete` for consistency with `Map` — but the solution of using static methods everywhere just to get that one name isn't worth the trouble.
